# Generated by Django 3.2.6 on 2021-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Bill_picture',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
