# Generated by Django 3.2.6 on 2021-11-18 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_bill_bill_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Bill_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Shop_address',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Shop_name',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Telephone_no',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Total_items',
            field=models.IntegerField(default=0),
        ),
    ]
