# Generated by Django 3.2.6 on 2021-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211118_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='username',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
