# Generated by Django 3.2.6 on 2021-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bill_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user_id',
        ),
    ]
