# Generated by Django 3.2.6 on 2021-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_bill_bill_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
