# Generated by Django 3.2.6 on 2021-12-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_bill_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='author',
        ),
    ]
