# Generated by Django 3.2.6 on 2021-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211206_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Telephone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
