# Generated by Django 3.2.6 on 2021-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_bill_telephone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
