# Generated by Django 3.2.6 on 2021-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_bill_bill_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Shop_name',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
