# Generated by Django 3.2.6 on 2021-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_bill_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Shop_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
